version: '3.8'

services:
  search-hits-backend:
    build:
      context: ./search-hits-backend
    container_name: search-hits-backend
    ports:
      - "8085:8085"
    networks:
      - search-hits-network

  search-hits-frontend:
    build:
      context: ./search-hits-frontend
    container_name: search-hits-frontend
    ports:
      - "4500:80"
    networks:
      - search-hits-network

networks:
  search-hits-network:
    driver: bridge
